// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc8e40ix8SH63R2TFRVHpDGRABSE9iUYs',
    appId: '1:954459124782:web:2479cf126f0e99a2479bbf',
    messagingSenderId: '954459124782',
    projectId: 'financial-tracker-afcca',
    authDomain: 'financial-tracker-afcca.firebaseapp.com',
    storageBucket: 'financial-tracker-afcca.firebasestorage.app',
    measurementId: 'G-RQ36F0T3QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxiDI95GTpwRkTWmyYd6ZS4oJP_ZRgCS8',
    appId: '1:954459124782:android:5a8676e3ea8e04d3479bbf',
    messagingSenderId: '954459124782',
    projectId: 'financial-tracker-afcca',
    storageBucket: 'financial-tracker-afcca.firebasestorage.app',
  );
}
